export const knownTables = [
  'alinea',
  'amendement',
  'article',
  'article_loi',
  'article_version',
  'intervention',
  'organisme',
  'parlementaire',
  'parlementaire_amendement',
  'parlementaire_organisme',
  'parlementaire_photo',
  'parlementaire_scrutin',
  'parlementaire_texteloi',
  'personnalite',
  'presence',
  'preuve_presence',
  'question_ecrite',
  'scrutin',
  'seance',
  'section',
  'tag',
  'tagging',
  'texteloi',
  'titre_loi',
  'variable_globale',
]

// missing in 13 and 14
// Differences:  [ 'parlementaire_scrutin', 'scrutin' ]
